/**
 *
 */
export const DEFAULT_THEME = 'white.green'

/**
 *
 */
export const THEMES_CHECK_DEFAULT_REQUEST = 'THEMES_CHECK_DEFAULT_REQUEST'
export const THEMES_CHECK_DEFAULT_SUCCESS = 'THEMES_CHECK_DEFAULT_SUCCESS'
export const THEMES_CHECK_DEFAULT_FAILURE = 'THEMES_CHECK_DEFAULT_FAILURE'

/**
 *
 */
export const THEMES_EDIT_REQUEST = 'THEMES_EDIT_REQUEST'
export const THEMES_EDIT_SUCCESS = 'THEMES_EDIT_SUCCESS'
export const THEMES_EDIT_FAILURE = 'THEMES_EDIT_FAILURE'
