export const SIGNUP_USERNAME_IDLE = 'SIGNUP_USERNAME_IDLE'
export const SIGNUP_USERNAME_REQUEST = 'SIGNUP_USERNAME_REQUEST'
export const SIGNUP_USERNAME_SUCCESS = 'SIGNUP_USERNAME_SUCCESS'
export const SIGNUP_USERNAME_FAILURE = 'SIGNUP_USERNAME_FAILURE'

export const SIGNUP_PHONE_IDLE = 'SIGNUP_PHONE_IDLE'
export const SIGNUP_PHONE_REQUEST = 'SIGNUP_PHONE_REQUEST'
export const SIGNUP_PHONE_SUCCESS = 'SIGNUP_PHONE_SUCCESS'
export const SIGNUP_PHONE_FAILURE = 'SIGNUP_PHONE_FAILURE'

export const SIGNUP_EMAIL_IDLE = 'SIGNUP_EMAIL_IDLE'
export const SIGNUP_EMAIL_REQUEST = 'SIGNUP_EMAIL_REQUEST'
export const SIGNUP_EMAIL_SUCCESS = 'SIGNUP_EMAIL_SUCCESS'
export const SIGNUP_EMAIL_FAILURE = 'SIGNUP_EMAIL_FAILURE'

export const SIGNUP_PASSWORD_IDLE = 'SIGNUP_PASSWORD_IDLE'
export const SIGNUP_PASSWORD_REQUEST = 'SIGNUP_PASSWORD_REQUEST'
export const SIGNUP_PASSWORD_SUCCESS = 'SIGNUP_PASSWORD_SUCCESS'
export const SIGNUP_PASSWORD_FAILURE = 'SIGNUP_PASSWORD_FAILURE'

export const SIGNUP_CREATE_IDLE = 'SIGNUP_CREATE_IDLE'
export const SIGNUP_CREATE_REQUEST = 'SIGNUP_CREATE_REQUEST'
export const SIGNUP_CREATE_SUCCESS = 'SIGNUP_CREATE_SUCCESS'
export const SIGNUP_CREATE_FAILURE = 'SIGNUP_CREATE_FAILURE'

export const SIGNUP_CONFIRM_IDLE = 'SIGNUP_CONFIRM_IDLE'
export const SIGNUP_CONFIRM_REQUEST = 'SIGNUP_CONFIRM_REQUEST'
export const SIGNUP_CONFIRM_SUCCESS = 'SIGNUP_CONFIRM_SUCCESS'
export const SIGNUP_CONFIRM_FAILURE = 'SIGNUP_CONFIRM_FAILURE'

export const SIGNUP_COGNITO_IDLE = 'SIGNUP_COGNITO_IDLE'
export const SIGNUP_COGNITO_REQUEST = 'SIGNUP_COGNITO_REQUEST'
export const SIGNUP_COGNITO_SUCCESS = 'SIGNUP_COGNITO_SUCCESS'
export const SIGNUP_COGNITO_FAILURE = 'SIGNUP_COGNITO_FAILURE'