export const PUSH_SET_APNS_TOKEN_REQUEST = 'PUSH_SET_APNS_TOKEN_REQUEST'
export const PUSH_SET_APNS_TOKEN_SUCCESS = 'PUSH_SET_APNS_TOKEN_SUCCESS'
export const PUSH_SET_APNS_TOKEN_FAILURE = 'PUSH_SET_APNS_TOKEN_FAILURE'

export const PUSH_START_REQUEST = 'PUSH_START_REQUEST'
export const PUSH_START_SUCCESS = 'PUSH_START_SUCCESS'
export const PUSH_START_FAILURE = 'PUSH_START_FAILURE'
