export const PUSH_SET_APNS_TOKEN_REQUEST = 'PUSH_SET_APNS_TOKEN_REQUEST'
export const PUSH_SET_APNS_TOKEN_SUCCESS = 'PUSH_SET_APNS_TOKEN_SUCCESS'
export const PUSH_SET_APNS_TOKEN_FAILURE = 'PUSH_SET_APNS_TOKEN_FAILURE'
