/**
 *
 */
export const POSTS_GET_REQUEST = 'POSTS_GET_REQUEST'
export const POSTS_GET_SUCCESS = 'POSTS_GET_SUCCESS'
export const POSTS_GET_FAILURE = 'POSTS_GET_FAILURE'
export const POSTS_GET_IDLE = 'POSTS_GET_IDLE'

export const POSTS_GET_MORE_REQUEST = 'POSTS_GET_MORE_REQUEST'
export const POSTS_GET_MORE_SUCCESS = 'POSTS_GET_MORE_SUCCESS'
export const POSTS_GET_MORE_FAILURE = 'POSTS_GET_MORE_FAILURE'
export const POSTS_GET_MORE_IDLE = 'POSTS_GET_MORE_IDLE'

export const POSTS_VIEWS_GET_IDLE = 'POSTS_VIEWS_GET_IDLE'
export const POSTS_VIEWS_GET_REQUEST = 'POSTS_VIEWS_GET_REQUEST'
export const POSTS_VIEWS_GET_SUCCESS = 'POSTS_VIEWS_GET_SUCCESS'
export const POSTS_VIEWS_GET_FAILURE = 'POSTS_VIEWS_GET_FAILURE'

/**
 *
 */
export const POSTS_FEED_GET_REQUEST = 'POSTS_FEED_GET_REQUEST'
export const POSTS_FEED_GET_SUCCESS = 'POSTS_FEED_GET_SUCCESS'
export const POSTS_FEED_GET_FAILURE = 'POSTS_FEED_GET_FAILURE'
export const POSTS_FEED_GET_IDLE = 'POSTS_FEED_GET_IDLE'

export const POSTS_FEED_GET_MORE_REQUEST = 'POSTS_FEED_GET_MORE_REQUEST'
export const POSTS_FEED_GET_MORE_SUCCESS = 'POSTS_FEED_GET_MORE_SUCCESS'
export const POSTS_FEED_GET_MORE_FAILURE = 'POSTS_FEED_GET_MORE_FAILURE'
export const POSTS_FEED_GET_MORE_IDLE = 'POSTS_FEED_GET_MORE_IDLE'

/**
 *
 */
export const POSTS_GET_ARCHIVED_REQUEST = 'POSTS_GET_ARCHIVED_REQUEST'
export const POSTS_GET_ARCHIVED_SUCCESS = 'POSTS_GET_ARCHIVED_SUCCESS'
export const POSTS_GET_ARCHIVED_FAILURE = 'POSTS_GET_ARCHIVED_FAILURE'
export const POSTS_GET_ARCHIVED_IDLE = 'POSTS_GET_ARCHIVED_IDLE'

export const POSTS_EDIT_REQUEST = 'POSTS_EDIT_REQUEST'
export const POSTS_EDIT_SUCCESS = 'POSTS_EDIT_SUCCESS'
export const POSTS_EDIT_FAILURE = 'POSTS_EDIT_FAILURE'
export const POSTS_EDIT_IDLE = 'POSTS_EDIT_IDLE'

export const POSTS_DELETE_REQUEST = 'POSTS_DELETE_REQUEST'
export const POSTS_DELETE_SUCCESS = 'POSTS_DELETE_SUCCESS'
export const POSTS_DELETE_FAILURE = 'POSTS_DELETE_FAILURE'
export const POSTS_DELETE_IDLE = 'POSTS_DELETE_IDLE'

export const POSTS_ARCHIVE_REQUEST = 'POSTS_ARCHIVE_REQUEST'
export const POSTS_ARCHIVE_SUCCESS = 'POSTS_ARCHIVE_SUCCESS'
export const POSTS_ARCHIVE_FAILURE = 'POSTS_ARCHIVE_FAILURE'
export const POSTS_ARCHIVE_IDLE = 'POSTS_ARCHIVE_IDLE'

export const POSTS_RESTORE_ARCHIVED_REQUEST = 'POSTS_RESTORE_ARCHIVED_REQUEST'
export const POSTS_RESTORE_ARCHIVED_SUCCESS = 'POSTS_RESTORE_ARCHIVED_SUCCESS'
export const POSTS_RESTORE_ARCHIVED_FAILURE = 'POSTS_RESTORE_ARCHIVED_FAILURE'
export const POSTS_RESTORE_ARCHIVED_IDLE = 'POSTS_RESTORE_ARCHIVED_IDLE'

export const POSTS_FLAG_REQUEST = 'POSTS_FLAG_REQUEST'
export const POSTS_FLAG_SUCCESS = 'POSTS_FLAG_SUCCESS'
export const POSTS_FLAG_FAILURE = 'POSTS_FLAG_FAILURE'
export const POSTS_FLAG_IDLE = 'POSTS_FLAG_IDLE'

export const POSTS_SINGLE_GET_REQUEST = 'POSTS_SINGLE_GET_REQUEST'
export const POSTS_SINGLE_GET_SUCCESS = 'POSTS_SINGLE_GET_SUCCESS'
export const POSTS_SINGLE_GET_FAILURE = 'POSTS_SINGLE_GET_FAILURE'
export const POSTS_SINGLE_GET_IDLE = 'POSTS_SINGLE_GET_IDLE'

export const POSTS_STORIES_GET_REQUEST = 'POSTS_STORIES_GET_REQUEST'
export const POSTS_STORIES_GET_SUCCESS = 'POSTS_STORIES_GET_SUCCESS'
export const POSTS_STORIES_GET_FAILURE = 'POSTS_STORIES_GET_FAILURE'
export const POSTS_STORIES_GET_IDLE = 'POSTS_STORIES_GET_IDLE'

export const POSTS_SHARE_REQUEST = 'POSTS_SHARE_REQUEST'
export const POSTS_SHARE_SUCCESS = 'POSTS_SHARE_SUCCESS'
export const POSTS_SHARE_FAILURE = 'POSTS_SHARE_FAILURE'
export const POSTS_SHARE_IDLE = 'POSTS_SHARE_IDLE'

export const POSTS_MEDIA_GET_REQUEST = 'POSTS_MEDIA_GET_REQUEST'
export const POSTS_MEDIA_GET_SUCCESS = 'POSTS_MEDIA_GET_SUCCESS'
export const POSTS_MEDIA_GET_FAILURE = 'POSTS_MEDIA_GET_FAILURE'
export const POSTS_MEDIA_GET_IDLE = 'POSTS_MEDIA_GET_IDLE'

export const POSTS_CREATE_REQUEST = 'POSTS_CREATE_REQUEST'
export const POSTS_CREATE_SUCCESS = 'POSTS_CREATE_SUCCESS'
export const POSTS_CREATE_FAILURE = 'POSTS_CREATE_FAILURE'
export const POSTS_CREATE_PROGRESS = 'POSTS_CREATE_PROGRESS'
export const POSTS_CREATE_IDLE = 'POSTS_CREATE_IDLE'

export const POSTS_CREATE_SCHEDULER_REQUEST = 'POSTS_CREATE_SCHEDULER_REQUEST'
export const POSTS_CREATE_SCHEDULER_SUCCESS = 'POSTS_CREATE_SCHEDULER_SUCCESS'
export const POSTS_CREATE_SCHEDULER_FAILURE = 'POSTS_CREATE_SCHEDULER_FAILURE'
export const POSTS_CREATE_SCHEDULER_IDLE = 'POSTS_CREATE_SCHEDULER_IDLE'

export const POSTS_ONYMOUSLY_LIKE_REQUEST = 'POSTS_ONYMOUSLY_LIKE_REQUEST'
export const POSTS_ONYMOUSLY_LIKE_SUCCESS = 'POSTS_ONYMOUSLY_LIKE_SUCCESS'
export const POSTS_ONYMOUSLY_LIKE_FAILURE = 'POSTS_ONYMOUSLY_LIKE_FAILURE'
export const POSTS_ONYMOUSLY_LIKE_IDLE = 'POSTS_ONYMOUSLY_LIKE_IDLE'

export const POSTS_ANONYMOUSLY_LIKE_REQUEST = 'POSTS_ANONYMOUSLY_LIKE_REQUEST'
export const POSTS_ANONYMOUSLY_LIKE_SUCCESS = 'POSTS_ANONYMOUSLY_LIKE_SUCCESS'
export const POSTS_ANONYMOUSLY_LIKE_FAILURE = 'POSTS_ANONYMOUSLY_LIKE_FAILURE'
export const POSTS_ANONYMOUSLY_LIKE_IDLE = 'POSTS_ANONYMOUSLY_LIKE_IDLE'

export const POSTS_DISLIKE_REQUEST = 'POSTS_DISLIKE_REQUEST'
export const POSTS_DISLIKE_SUCCESS = 'POSTS_DISLIKE_SUCCESS'
export const POSTS_DISLIKE_FAILURE = 'POSTS_DISLIKE_FAILURE'
export const POSTS_DISLIKE_IDLE = 'POSTS_DISLIKE_IDLE'

export const POSTS_REPORT_POST_VIEWS_REQUEST = 'POSTS_REPORT_POST_VIEWS_REQUEST'
export const POSTS_REPORT_POST_VIEWS_SUCCESS = 'POSTS_REPORT_POST_VIEWS_SUCCESS'
export const POSTS_REPORT_POST_VIEWS_FAILURE = 'POSTS_REPORT_POST_VIEWS_FAILURE'
export const POSTS_REPORT_POST_VIEWS_IDLE = 'POSTS_REPORT_POST_VIEWS_IDLE'

export const POSTS_GET_TRENDING_POSTS_REQUEST = 'POSTS_GET_TRENDING_POSTS_REQUEST'
export const POSTS_GET_TRENDING_POSTS_SUCCESS = 'POSTS_GET_TRENDING_POSTS_SUCCESS'
export const POSTS_GET_TRENDING_POSTS_FAILURE = 'POSTS_GET_TRENDING_POSTS_FAILURE'
export const POSTS_GET_TRENDING_POSTS_IDLE = 'POSTS_GET_TRENDING_POSTS_IDLE'

export const POSTS_GET_TRENDING_POSTS_MORE_REQUEST = 'POSTS_GET_TRENDING_POSTS_MORE_REQUEST'
export const POSTS_GET_TRENDING_POSTS_MORE_SUCCESS = 'POSTS_GET_TRENDING_POSTS_MORE_SUCCESS'
export const POSTS_GET_TRENDING_POSTS_MORE_FAILURE = 'POSTS_GET_TRENDING_POSTS_MORE_FAILURE'
export const POSTS_GET_TRENDING_POSTS_MORE_IDLE = 'POSTS_GET_TRENDING_POSTS_MORE_IDLE'

/**
 * 
 */
export const POSTS_COMMENTS_GET_REQUEST = 'POSTS_COMMENTS_GET_REQUEST'
export const POSTS_COMMENTS_GET_SUCCESS = 'POSTS_COMMENTS_GET_SUCCESS'
export const POSTS_COMMENTS_GET_FAILURE = 'POSTS_COMMENTS_GET_FAILURE'
export const POSTS_COMMENTS_GET_IDLE = 'POSTS_COMMENTS_GET_IDLE'

export const COMMENTS_ADD_REQUEST = 'COMMENTS_ADD_REQUEST'
export const COMMENTS_ADD_SUCCESS = 'COMMENTS_ADD_SUCCESS'
export const COMMENTS_ADD_FAILURE = 'COMMENTS_ADD_FAILURE'
export const COMMENTS_ADD_IDLE = 'COMMENTS_ADD_IDLE'