export const CHAT_GET_CHATS_IDLE = 'CHAT_GET_CHATS_IDLE'
export const CHAT_GET_CHATS_REQUEST = 'CHAT_GET_CHATS_REQUEST'
export const CHAT_GET_CHATS_SUCCESS = 'CHAT_GET_CHATS_SUCCESS'
export const CHAT_GET_CHATS_FAILURE = 'CHAT_GET_CHATS_FAILURE'

export const CHAT_GET_CHAT_IDLE = 'CHAT_GET_CHAT_IDLE'
export const CHAT_GET_CHAT_REQUEST = 'CHAT_GET_CHAT_REQUEST'
export const CHAT_GET_CHAT_SUCCESS = 'CHAT_GET_CHAT_SUCCESS'
export const CHAT_GET_CHAT_FAILURE = 'CHAT_GET_CHAT_FAILURE'

export const CHAT_CREATE_DIRECT_IDLE = 'CHAT_CREATE_DIRECT_IDLE'
export const CHAT_CREATE_DIRECT_REQUEST = 'CHAT_CREATE_DIRECT_REQUEST'
export const CHAT_CREATE_DIRECT_SUCCESS = 'CHAT_CREATE_DIRECT_SUCCESS'
export const CHAT_CREATE_DIRECT_FAILURE = 'CHAT_CREATE_DIRECT_FAILURE'

export const CHAT_ADD_MESSAGE_IDLE = 'CHAT_ADD_MESSAGE_IDLE'
export const CHAT_ADD_MESSAGE_REQUEST = 'CHAT_ADD_MESSAGE_REQUEST'
export const CHAT_ADD_MESSAGE_SUCCESS = 'CHAT_ADD_MESSAGE_SUCCESS'
export const CHAT_ADD_MESSAGE_FAILURE = 'CHAT_ADD_MESSAGE_FAILURE'

export const CHAT_REPORT_VIEW_IDLE = 'CHAT_REPORT_VIEW_IDLE'
export const CHAT_REPORT_VIEW_REQUEST = 'CHAT_REPORT_VIEW_REQUEST'
export const CHAT_REPORT_VIEW_SUCCESS = 'CHAT_REPORT_VIEW_SUCCESS'
export const CHAT_REPORT_VIEW_FAILURE = 'CHAT_REPORT_VIEW_FAILURE'

export const CHAT_DELETE_MESSAGE_IDLE = 'CHAT_DELETE_MESSAGE_IDLE'
export const CHAT_DELETE_MESSAGE_REQUEST = 'CHAT_DELETE_MESSAGE_REQUEST'
export const CHAT_DELETE_MESSAGE_SUCCESS = 'CHAT_DELETE_MESSAGE_SUCCESS'
export const CHAT_DELETE_MESSAGE_FAILURE = 'CHAT_DELETE_MESSAGE_FAILURE'

export const CHAT_FLAG_MESSAGE_IDLE = 'CHAT_FLAG_MESSAGE_IDLE'
export const CHAT_FLAG_MESSAGE_REQUEST = 'CHAT_FLAG_MESSAGE_REQUEST'
export const CHAT_FLAG_MESSAGE_SUCCESS = 'CHAT_FLAG_MESSAGE_SUCCESS'
export const CHAT_FLAG_MESSAGE_FAILURE = 'CHAT_FLAG_MESSAGE_FAILURE'
