export const ALBUMS_GET_IDLE = 'ALBUMS_GET_IDLE'
export const ALBUMS_GET_REQUEST = 'ALBUMS_GET_REQUEST'
export const ALBUMS_GET_SUCCESS = 'ALBUMS_GET_SUCCESS'
export const ALBUMS_GET_FAILURE = 'ALBUMS_GET_FAILURE'

export const ALBUMS_SINGLE_GET_IDLE = 'ALBUMS_SINGLE_GET_IDLE'
export const ALBUMS_SINGLE_GET_REQUEST = 'ALBUMS_SINGLE_GET_REQUEST'
export const ALBUMS_SINGLE_GET_SUCCESS = 'ALBUMS_SINGLE_GET_SUCCESS'
export const ALBUMS_SINGLE_GET_FAILURE = 'ALBUMS_SINGLE_GET_FAILURE'

export const ALBUMS_POSTS_GET_IDLE = 'ALBUMS_POSTS_GET_IDLE'
export const ALBUMS_POSTS_GET_REQUEST = 'ALBUMS_POSTS_GET_REQUEST'
export const ALBUMS_POSTS_GET_SUCCESS = 'ALBUMS_POSTS_GET_SUCCESS'
export const ALBUMS_POSTS_GET_FAILURE = 'ALBUMS_POSTS_GET_FAILURE'

export const ALBUMS_POSTS_GET_MORE_IDLE = 'ALBUMS_POSTS_GET_MORE_IDLE'
export const ALBUMS_POSTS_GET_MORE_REQUEST = 'ALBUMS_POSTS_GET_MORE_REQUEST'
export const ALBUMS_POSTS_GET_MORE_SUCCESS = 'ALBUMS_POSTS_GET_MORE_SUCCESS'
export const ALBUMS_POSTS_GET_MORE_FAILURE = 'ALBUMS_POSTS_GET_MORE_FAILURE'

export const ALBUMS_CREATE_IDLE = 'ALBUMS_CREATE_IDLE'
export const ALBUMS_CREATE_REQUEST = 'ALBUMS_CREATE_REQUEST'
export const ALBUMS_CREATE_SUCCESS = 'ALBUMS_CREATE_SUCCESS'
export const ALBUMS_CREATE_FAILURE = 'ALBUMS_CREATE_FAILURE'

export const ALBUMS_EDIT_IDLE = 'ALBUMS_EDIT_IDLE'
export const ALBUMS_EDIT_REQUEST = 'ALBUMS_EDIT_REQUEST'
export const ALBUMS_EDIT_SUCCESS = 'ALBUMS_EDIT_SUCCESS'
export const ALBUMS_EDIT_FAILURE = 'ALBUMS_EDIT_FAILURE'

export const ALBUMS_DELETE_IDLE = 'ALBUMS_DELETE_IDLE'
export const ALBUMS_DELETE_REQUEST = 'ALBUMS_DELETE_REQUEST'
export const ALBUMS_DELETE_SUCCESS = 'ALBUMS_DELETE_SUCCESS'
export const ALBUMS_DELETE_FAILURE = 'ALBUMS_DELETE_FAILURE'
