export const ALBUMS_CREATE_IDLE = 'ALBUMS_CREATE_IDLE'
export const ALBUMS_CREATE_REQUEST = 'ALBUMS_CREATE_REQUEST'
export const ALBUMS_CREATE_SUCCESS = 'ALBUMS_CREATE_SUCCESS'
export const ALBUMS_CREATE_FAILURE = 'ALBUMS_CREATE_FAILURE'

export const ALBUMS_EDIT_IDLE = 'ALBUMS_EDIT_IDLE'
export const ALBUMS_EDIT_REQUEST = 'ALBUMS_EDIT_REQUEST'
export const ALBUMS_EDIT_SUCCESS = 'ALBUMS_EDIT_SUCCESS'
export const ALBUMS_EDIT_FAILURE = 'ALBUMS_EDIT_FAILURE'

export const ALBUMS_DELETE_IDLE = 'ALBUMS_DELETE_IDLE'
export const ALBUMS_DELETE_REQUEST = 'ALBUMS_DELETE_REQUEST'
export const ALBUMS_DELETE_SUCCESS = 'ALBUMS_DELETE_SUCCESS'
export const ALBUMS_DELETE_FAILURE = 'ALBUMS_DELETE_FAILURE'
