/**
 *
 */
export const PROMO_CODES_REDEEM_REQUEST = 'PROMO_CODES_REDEEM_REQUEST'
export const PROMO_CODES_REDEEM_SUCCESS = 'PROMO_CODES_REDEEM_SUCCESS'
export const PROMO_CODES_REDEEM_FAILURE = 'PROMO_CODES_REDEEM_FAILURE'
