export const CAMERA_CAPTURE_REQUEST = 'CAMERA_CAPTURE_REQUEST'
export const CAMERA_CAPTURE_SUCCESS = 'CAMERA_CAPTURE_SUCCESS'
export const CAMERA_CAPTURE_FAILURE = 'CAMERA_CAPTURE_FAILURE'
export const CAMERA_CAPTURE_LOADING = 'CAMERA_CAPTURE_LOADING'
export const CAMERA_CAPTURE_IDLE = 'CAMERA_CAPTURE_IDLE'

export const CHANGE_RECORDING_STATE = 'CHANGE_RECORDING_STATE'
