require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '12.0'

target 'REAL' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts.podspec"
  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'
  pod 'RSKImageCropper', '2.0.0'
  pod 'GoogleSignIn', '~> 5.0.0'
  
  target 'REALTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!('Flipper' => '0.54.0')
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'REAL-tvOS' do
  target 'REAL-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
