export const SUBSCRIPTIONS_MAIN_REQUEST = 'SUBSCRIPTIONS_MAIN_REQUEST'
export const SUBSCRIPTIONS_MAIN_SUCCESS = 'SUBSCRIPTIONS_MAIN_SUCCESS'
export const SUBSCRIPTIONS_MAIN_FAILURE = 'SUBSCRIPTIONS_MAIN_FAILURE'
export const SUBSCRIPTIONS_MAIN_IDLE = 'SUBSCRIPTIONS_MAIN_IDLE'

export const SUBSCRIPTIONS_POLL_REQUEST = 'SUBSCRIPTIONS_POLL_REQUEST'
export const SUBSCRIPTIONS_POLL_SUCCESS = 'SUBSCRIPTIONS_POLL_SUCCESS'
export const SUBSCRIPTIONS_POLL_FAILURE = 'SUBSCRIPTIONS_POLL_FAILURE'
export const SUBSCRIPTIONS_POLL_IDLE = 'SUBSCRIPTIONS_POLL_IDLE'
