export const SUBSCRIPTIONS_MAIN_REQUEST = 'SUBSCRIPTIONS_MAIN_REQUEST'
export const SUBSCRIPTIONS_MAIN_IDLE = 'SUBSCRIPTIONS_MAIN_IDLE'

export const SUBSCRIPTIONS_POLL_REQUEST = 'SUBSCRIPTIONS_POLL_REQUEST'
export const SUBSCRIPTIONS_POLL_IDLE = 'SUBSCRIPTIONS_POLL_IDLE'

export const SUBSCRIPTIONS_POST_COMPLETED = 'SUBSCRIPTIONS_POST_COMPLETED'
export const SUBSCRIPTIONS_POST_ERROR = 'SUBSCRIPTIONS_POST_ERROR'
