export const SUBSCRIPTION_MAIN_START = 'SUBSCRIPTION_MAIN_START'
export const SUBSCRIPTION_MAIN_STOP = 'SUBSCRIPTION_MAIN_STOP'
export const SUBSCRIPTION_MAIN_ERROR = 'SUBSCRIPTION_MAIN_ERROR'

export const SUBSCRIPTION_POLL_START = 'SUBSCRIPTION_POLL_START'
export const SUBSCRIPTION_POLL_STOP = 'SUBSCRIPTION_POLL_STOP'
export const SUBSCRIPTION_POLL_ERROR = 'SUBSCRIPTION_POLL_ERROR'
