export const PRIMARY_SUBSCRIPTION = 'app.real.mobile.diamond1M'

export const SUBSCRIPTION_LEVEL = {
  DIAMOND: 'DIAMOND',
}

/**
 *
 */
export const PURCHASE_REQUEST = 'PURCHASE_REQUEST'
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS'
export const PURCHASE_FAILURE = 'PURCHASE_FAILURE'

/**
 *
 */
export const RETRY_PURCHASE_REQUEST = 'RETRY_PURCHASE_REQUEST'
export const RETRY_PURCHASE_SUCCESS = 'RETRY_PURCHASE_SUCCESS'
export const RETRY_PURCHASE_FAILURE = 'RETRY_PURCHASE_FAILURE'
