export const APP_READY_IDLE = 'APP_READY_IDLE'
export const APP_READY_REQUEST = 'APP_READY_REQUEST'
export const APP_READY_SUCCESS = 'APP_READY_SUCCESS'
export const APP_READY_FAILURE = 'APP_READY_FAILURE'
