export const APP_READY_IDLE = 'APP_READY_IDLE'
export const APP_READY_REQUEST = 'APP_READY_REQUEST'
export const APP_READY_SUCCESS = 'APP_READY_SUCCESS'
export const APP_READY_FAILURE = 'APP_READY_FAILURE'

export const APP_TRANSLATION_REQUEST = 'APP_TRANSLATION_REQUEST'
export const APP_TRANSLATION_SUCCESS = 'APP_TRANSLATION_SUCCESS'
export const APP_TRANSLATION_FAILURE = 'APP_TRANSLATION_FAILURE'
export const APP_TRANSLATION_IDLE = 'APP_TRANSLATION_IDLE'
