export const CONTACTS_GET_REQUEST = 'CONTACTS_GET_REQUEST'
export const CONTACTS_GET_SUCCESS = 'CONTACTS_GET_SUCCESS'
export const CONTACTS_GET_FAILURE = 'CONTACTS_GET_FAILURE'

export const CONTACTS_INVITE_REQUEST = 'CONTACTS_INVITE_REQUEST'
export const CONTACTS_INVITE_SUCCESS = 'CONTACTS_INVITE_SUCCESS'
export const CONTACTS_INVITE_FAILURE = 'CONTACTS_INVITE_FAILURE'
export const CONTACTS_INVITE_IDLE = 'CONTACTS_INVITE_IDLE'

export const CONTACTS_FOLLOW_REQUEST = 'CONTACTS_FOLLOW_REQUEST'
export const CONTACTS_FOLLOW_SUCCESS = 'CONTACTS_FOLLOW_SUCCESS'
export const CONTACTS_FOLLOW_FAILURE = 'CONTACTS_FOLLOW_FAILURE'
