export const CONTACTS_GET_REQUEST = 'CONTACTS_GET_REQUEST'
export const CONTACTS_GET_SUCCESS = 'CONTACTS_GET_SUCCESS'
export const CONTACTS_GET_FAILURE = 'CONTACTS_GET_FAILURE'
export const CONTACTS_GET_IDLE = 'CONTACTS_GET_IDLE'