export const CONTACTS_GET_REQUEST = 'CONTACTS_GET_REQUEST'
export const CONTACTS_GET_SUCCESS = 'CONTACTS_GET_SUCCESS'
export const CONTACTS_GET_FAILURE = 'CONTACTS_GET_FAILURE'

export const CONTACTS_INVITE_REQUEST = 'CONTACTS_INVITE_REQUEST'
export const CONTACTS_INVITE_SUCCESS = 'CONTACTS_INVITE_SUCCESS'
export const CONTACTS_INVITE_FAILURE = 'CONTACTS_INVITE_FAILURE'