export const LAYOUT_POSTS_LIST_ITEM_SUCCESS = 'LAYOUT_POSTS_LIST_ITEM_SUCCESS'
export const LAYOUT_POSTS_LIST_ITEM_IDLE = 'LAYOUT_POSTS_LIST_ITEM_IDLE'
export const LAYOUT_POSTS_LIST_SCROLL_SUCCESS = 'LAYOUT_POSTS_LIST_SCROLL_SUCCESS'
export const LAYOUT_POSTS_LIST_SCROLL_IDLE = 'LAYOUT_POSTS_LIST_SCROLL_IDLE'

export const LAYOUT_POST_MEDIA_ITEM_SUCCESS = 'LAYOUT_POST_MEDIA_ITEM_SUCCESS'
export const LAYOUT_POST_MEDIA_ITEM_IDLE = 'LAYOUT_POST_MEDIA_ITEM_IDLE'
export const LAYOUT_POST_MEDIA_SCROLL_SUCCESS = 'LAYOUT_POST_MEDIA_SCROLL_SUCCESS'
export const LAYOUT_POST_MEDIA_SCROLL_IDLE = 'LAYOUT_POST_MEDIA_SCROLL_IDLE'